apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-config
  namespace: {{ .Values.namespace.name }}
data:
  APP_DOMAIN: {{ .Values.global.appDomain }}
  API_DOMAIN: {{ .Values.global.apiDomain }}
  LOG_LEVEL: {{ .Values.logging.level }}
