yaml.schemas:
  https://json.schemastore.org/github-workflow.json: .github/workflows/*.yml
  https://json.schemastore.org/github-action.json: .github/action.yml

yaml.validate: true
yaml.format.enable: true
